name: Go

on:
  push:
    branches: [ "master", "main", "refactor/*" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -tags nosqlite -v ./...

    - name: Test
      run: go test -tags nosqlite -v ./...
